### ISSUE TITLE
Can't find L0 regularization implementation.

### ISSUE THREAD

**Issue by Alice01010101** [Allen0307/AdapterBias#1]
Hello, I cannot find the implementation of L0 regularization, which is mentioned in your paper. Could you please show me where it is?

**Comment by Allen0307** [comment]
Hi, Alice. Our implementation of L0 regularization is the same as diff-pruning(https://arxiv.org/abs/2012.07463). The  similar code could be found in here(https://github.com/dguo98/DiffPruning/blob/main/examples/run_glue_diffpruning.py). Thanks!
