### ISSUE TITLE
Parameter size   

### ISSUE THREAD

**Issue by xuguangyi1999** [Allen0307/AdapterBias#5]
Hello, may I ask the L Linear transformation in your AdapterBias self.adapter_alpha = nn.Linear(? ,?) What are the inputs and outputs? Why are you so small? I Linear transform self.adapter_alpha = nn.Linear(3072,768) Input 3072, output 768 has 28M parameters.
你好，请问你们的AdapterBias里面L线性变换self.adapter_alpha = nn.Linear(？,？)输入输出是多少？为什么你们参数量这么小，我L线性变换self.adapter_alpha = nn.Linear(3072,768)输入3072，输出768有28M参数。

**Comment by Allen0307** [comment]
Hi, the output dimension of L should be 1. In your case, L should be self.adapter_alpha = nn.Linear(3072,1).

**Comment by xuguangyi1999** [comment]
ok,thank you!
